name: openMINDS_validation

on:
  push:
    branches:
      - v3
  pull_request:
    branches:
      - v3

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Checkout central repo
      uses: actions/checkout@v2
      with:
        repository: HumanBrainProject/openMINDS
        ref: master
        path: openMINDScentral
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f openMINDScentral/requirements.txt ]; then pip install -r openMINDScentral/requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Validate schemas
      run: |
        if [ -f openMINDScentral/requirements.txt ]; then pip install -r openMINDScentral/requirements.txt; fi
        python openMINDScentral/validator/schema_validator.py
    - name: Run generation
        run: |
          python openMINDScentral/openMINDS.py
    - name: Test with pytest
      run: |
        pytest
    - name: Archive expanded version
      uses: actions/upload-artifact@v2
      with:
        name: expanded schema templates
        path: |
          expanded
    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: target files
        path: |
          target
